azure-pipeline/build-artifacts-and-run-tests-job.yaml, azure-pipeline/build-steps.yaml, azure-pipeline/install-dependencies-steps.yaml, azure-pipeline/run-tests-job.yaml, azure-pipeline/test-steps.yaml, build.yaml, jest.ci.js, package.json, packages/common/src/build-utilities/monorepo-packages.spec.ts, packages/resource-deployment/package.json, packages/resource-deployment/scripts/create-resource-group.sh, packages/resource-deployment/scripts/delete-resource-group.sh, packages/resource-deployment/scripts/get-resource-name-from-resource-paths.sh, packages/resource-deployment/scripts/install.sh, packages/resource-deployment/scripts/process-utilities.sh, packages/resource-deployment/scripts/wait-for-deployment.sh, packages/resource-deployment/scripts/wait-for-pending-deployments.sh, yarn.lock
Add yaml files for ADO build pipeline and some basic resource deployment scripts. The deployment scripts currently only create an empty resource group.
Create build and deployment pipelines for development of the service
=> chore: build and deployment pipeline scripts

azure-pipeline/TSAOptions.json
Add config file for TSA upload task
This file is required for the latest version of TSA upload
=> chore: add TSAOptions.json

packages/resource-deployment/scripts/create-cosmos-db.sh, packages/resource-deployment/scripts/install.sh, packages/resource-deployment/templates/cosmos-db.template.json
Adds cosmosdb deployment as part of installation script
Create a cosmos account for website and scan metadata repositories
=> deploy cosmosdb

package.json, packages/storage-documents/package.json, yarn.lock
=> Patch security issues

package.json, yarn.lock
=> Added npm audit fix support

.prettierignore, .vscode/workspace.code-workspace, packages/resource-deployment/helm-charts/storage-web-api/.helmignore, packages/resource-deployment/helm-charts/storage-web-api/Chart.yaml, packages/resource-deployment/helm-charts/storage-web-api/templates/_helpers.tpl, packages/resource-deployment/helm-charts/storage-web-api/templates/deployment.yaml, packages/resource-deployment/helm-charts/storage-web-api/templates/service.yaml, packages/resource-deployment/helm-charts/storage-web-api/templates/tests/test-connection.yaml, packages/resource-deployment/helm-charts/storage-web-api/values-ci.yaml, packages/resource-deployment/helm-charts/storage-web-api/values-ppe.yaml, packages/resource-deployment/helm-charts/storage-web-api/values-prod.yaml, packages/resource-deployment/helm-charts/storage-web-api/values.yaml, packages/resource-deployment/scripts/create-cosmos-db.sh, packages/resource-deployment/scripts/create-key-vault.sh, packages/resource-deployment/scripts/create-kubernetes-service.sh, packages/resource-deployment/scripts/install-service-manifest.sh, packages/resource-deployment/scripts/install-storage-web-api.sh, packages/resource-deployment/scripts/install.sh, packages/resource-deployment/scripts/push-image-to-container-registry.sh, packages/resource-deployment/scripts/role-assign-for-sp.sh, packages/resource-deployment/scripts/wait-for-pending-deployments.sh
Deployment script to install kubernetes manifest. Includes:
- helm chart to install storage web api service
- bash script to install helm chart
- bash script clean up 
Release pipeline integration will be done in a next step
=> Deployment script to install kubernetes manifest

packages/resource-deployment/helm-charts/storage-web-api/templates/deployment.yaml, packages/resource-deployment/package.json, packages/resource-deployment/scripts/install-service-manifest.sh, packages/resource-deployment/scripts/install.sh
Enable service install in deployment script
[Validation](https://dev.azure.com/web-insights-private/Web%20Insights%20(private)/_releaseProgress?_a=release-pipeline-progress&releaseId=98)
=> Enable service install in deployment script

packages/api-contracts/src/index.ts, packages/api-contracts/src/types/page-update.ts, packages/api-contracts/src/validators/validate-page-update.ts, packages/integration-tests/package.json, packages/integration-tests/tests/api-contracts/validate-page-update.spec.ts, packages/integration-tests/tests/api-contracts/validate-website.spec.ts, packages/storage-documents/src/page.ts, packages/storage-web-api/src/controllers/post-website-controller.ts, packages/storage-web-api/src/controllers/update-page-controller.spec.ts, packages/storage-web-api/src/controllers/update-page-controller.ts, packages/storage-web-api/src/converters/page-document-response-converter.spec.ts, packages/storage-web-api/src/converters/page-document-response-converter.ts, packages/storage-web-api/src/converters/website-document-response-converter.ts, packages/storage-web-api/src/request-validators/update-page-request-validator.spec.ts, packages/storage-web-api/src/request-validators/update-page-request-validator.ts, packages/storage-web-api/update-page-func/function.json, packages/storage-web-api/update-page-func/index.ts
- Add a flag to page documents to disable scans
- Create an endpoint to update page documents to set or change this flag
Allow users to disable scans for certain pages, for example if the page consistently causes errors
=> UpdatePage API endpoint

packages/resource-deployment/helm-charts/storage-web-api/values.yaml, packages/resource-deployment/scripts/create-certificate.sh, packages/resource-deployment/scripts/create-kubernetes-service.sh, packages/resource-deployment/scripts/create-public-network.sh, packages/resource-deployment/scripts/get-resource-names.sh, packages/resource-deployment/scripts/install-service-manifest.sh, packages/resource-deployment/scripts/install-storage-web-api.sh, packages/resource-deployment/templates/certificate-policy.template.json
Added frontend public DNS in format `wisapi<deployment id>.<region>.cloudapp.azure.com`
Added HTTPS protocol for AKS cluster for frontend public endpoint.
Create self signed certificate to support SSL encryption
=> Added support for public TLS

packages/resource-deployment/scripts/install.sh
Add network deployment to global install script
=> Add network deployment to global install script

packages/resource-deployment/scripts/create-public-network.sh
Remove unnecessary call to keyvault to generate secret id
=> Update secret id generation

packages/resource-deployment/scripts/create-public-network.sh
Restrict the min TLS version to 1.2 for app gateway
We are required to only use TLS 1.2 and disallow TLS 1.0 and 1.1
=> Require TLS 1.2 for app gateway

packages/resource-deployment/scripts/create-kubernetes-service.sh
Fix a bug in role id query
Fixes a bug that occurs on first-time deployment to a dev resource group
=> Fix bug in role id query

package.json, packages/api-contracts/package.json, packages/azure-services/package.json, packages/common/package.json, packages/integration-tests/package.json, packages/logger/package.json, packages/service-library/package.json, packages/storage-documents/package.json, packages/storage-web-api/package.json, yarn.lock
This PR was created by the Combine PRs action by combining the following PRs:
* #272 chore(deps-dev): bump @types/lodash from 4.14.170 to 4.14.173
* #268 chore(deps-dev): bump jest-junit from 12.2.0 to 12.3.0
=> Update combined dependencies

package.json, yarn.lock
Resolve ansi-regex to v5.0.1
Fixes a dependabot alert
=> chore: ansi-regex v5.0.1

.vscode/workspace.code-workspace, packages/common/src/build-utilities/monorepo-packages.spec.ts, packages/storage-api-client/jest.config.js, packages/storage-api-client/package.json, packages/storage-api-client/prettier.config.js, packages/storage-api-client/src/index.ts, packages/storage-api-client/src/web-insights-storage-client.spec.ts, packages/storage-api-client/src/web-insights-storage-client.ts, packages/storage-api-client/tsconfig.json, yarn.lock
Create a client to call the storage API
This will be used in our E2E tests to test the storage API
=> Storage API client

DEVELOPMENT.md, packages/api-contracts/package.json, packages/azure-services/package.json, packages/integration-tests/package.json, packages/logger/package.json, packages/service-library/package.json, packages/storage-api-client/package.json, packages/storage-documents/package.json, packages/storage-web-api/package.json
=> Development setup steps

packages/resource-deployment/scripts/push-secrets-to-key-vault.sh
=> Fix issuer URI format

azure-pipeline/build-artifacts-and-run-tests-job.yaml
Copy the built e2e-test-runner files into the staging directory in the build pipeline
Fix failures in the canary deployment pipeline
=> Copy e2e-test-runner files in pipeline

packages/resource-deployment/scripts/create-dashboard.sh, packages/resource-deployment/scripts/install.sh, packages/resource-deployment/templates/dashboard.template.json
Creates a monitoring dashboard for the Web Insights Service ([Example dashboard](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/dashboard/arm/subscriptions/7bb42229-b02f-47cb-bd95-a115b9c5b775/resourceGroups/kepowneltest2/providers/Microsoft.Portal/dashboards/wisdashboardmyzbjbtbxnco6))
To allow devs to more easily detect issues with the Web Insights Service
=> Create monitoring dashboard

.vscode/workspace.code-workspace, azure-pipeline/build-artifacts-and-run-tests-job.yaml, packages/common/src/build-utilities/monorepo-packages.spec.ts, packages/health-client/jest.config.js, packages/health-client/package.json, packages/health-client/prettier.config.js, packages/health-client/src/deployment-health-checker.spec.ts, packages/health-client/src/deployment-health-checker.ts, packages/health-client/src/health-checker.ts, packages/health-client/tsconfig.json, packages/health-client/webpack.config.js, packages/storage-api-client/src/index.ts, packages/storage-api-client/src/web-insights-storage-client.spec.ts, packages/storage-api-client/src/web-insights-storage-client.ts, yarn.lock
Create a node script that uses the Web Insights storage API client to poll the health check endpoint and wait for a successful result.
This script will be used in the deployment pipeline to wait for E2E test completion and fail the pipeline if tests do not succeed within a timeout period.
=> Health check client
